[2023-04-23T15:22:27.072+0200] {processor.py:153} INFO - Started process (PID=50365) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:22:27.078+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T15:22:27.079+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:22:27.079+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:22:27.148+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:22:27.146+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T15:22:27.148+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:22:27.148+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T15:22:27.149+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:22:29.547+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 2.476 seconds
[2023-04-23T15:26:32.274+0200] {processor.py:153} INFO - Started process (PID=50451) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:26:32.281+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T15:26:32.282+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:26:32.282+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:26:32.357+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:26:32.356+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T15:26:32.357+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:26:32.357+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T15:26:32.358+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:26:33.637+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.364 seconds
[2023-04-23T15:29:30.430+0200] {processor.py:153} INFO - Started process (PID=50508) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:29:30.439+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T15:29:30.440+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:29:30.439+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:29:30.526+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:29:30.526+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T15:29:30.527+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:29:30.527+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T15:29:30.527+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:29:32.041+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.612 seconds
[2023-04-23T15:34:31.308+0200] {processor.py:153} INFO - Started process (PID=50647) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:34:31.316+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T15:34:31.322+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:34:31.319+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:34:31.483+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:34:31.472+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T15:34:31.484+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:34:31.484+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T15:34:31.485+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:34:34.475+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 3.175 seconds
[2023-04-23T15:40:01.934+0200] {processor.py:153} INFO - Started process (PID=50804) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:40:01.940+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T15:40:01.942+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:40:01.941+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:40:02.015+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:40:02.015+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T15:40:02.016+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:40:02.016+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T15:40:02.016+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:40:04.218+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 2.284 seconds
[2023-04-23T15:43:51.447+0200] {processor.py:153} INFO - Started process (PID=50892) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:43:51.453+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T15:43:51.454+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:43:51.453+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:43:51.531+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:43:51.530+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T15:43:51.531+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:43:51.531+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T15:43:51.532+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:43:53.218+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.772 seconds
[2023-04-23T15:48:31.634+0200] {processor.py:153} INFO - Started process (PID=51035) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:48:31.642+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T15:48:31.644+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:48:31.644+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:48:31.734+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:48:31.732+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T15:48:31.735+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:48:31.735+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T15:48:31.735+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:48:34.215+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 2.582 seconds
[2023-04-23T15:51:55.113+0200] {processor.py:153} INFO - Started process (PID=51167) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:51:55.119+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T15:51:55.120+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:51:55.120+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:51:55.174+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:51:55.174+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T15:51:55.175+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:51:55.175+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T15:51:55.175+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:51:56.025+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.914 seconds
[2023-04-23T15:54:17.568+0200] {processor.py:153} INFO - Started process (PID=51255) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:54:17.573+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T15:54:17.573+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:54:17.573+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:54:17.626+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:54:17.625+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T15:54:17.626+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:54:17.626+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T15:54:17.627+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:54:18.500+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.934 seconds
[2023-04-23T15:58:50.924+0200] {processor.py:153} INFO - Started process (PID=51512) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:58:50.928+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T15:58:50.929+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:58:50.929+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:58:50.981+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:58:50.980+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T15:58:50.981+0200] {logging_mixin.py:137} INFO - [2023-04-23T15:58:50.981+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T15:58:50.981+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T15:58:52.055+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.131 seconds
[2023-04-23T16:02:30.096+0200] {processor.py:153} INFO - Started process (PID=51744) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:02:30.101+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T16:02:30.101+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:02:30.101+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:02:30.149+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:02:30.148+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T16:02:30.149+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:02:30.149+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T16:02:30.149+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:02:30.943+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.848 seconds
[2023-04-23T16:06:32.127+0200] {processor.py:153} INFO - Started process (PID=51975) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:06:32.132+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T16:06:32.133+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:06:32.133+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:06:32.180+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:06:32.179+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T16:06:32.180+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:06:32.180+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T16:06:32.180+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:06:33.551+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.424 seconds
[2023-04-23T16:13:13.905+0200] {processor.py:153} INFO - Started process (PID=52400) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:13:13.911+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T16:13:13.912+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:13:13.912+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:13:13.977+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:13:13.977+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T16:13:13.978+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:13:13.978+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T16:13:13.979+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:13:15.010+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.106 seconds
[2023-04-23T16:15:20.138+0200] {processor.py:153} INFO - Started process (PID=52521) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:15:20.141+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T16:15:20.141+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:15:20.141+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:15:20.176+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:15:20.175+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T16:15:20.176+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:15:20.176+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T16:15:20.176+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:15:20.811+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.674 seconds
[2023-04-23T16:18:33.248+0200] {processor.py:153} INFO - Started process (PID=52752) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:18:33.251+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T16:18:33.251+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:18:33.251+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:18:33.289+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:18:33.289+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T16:18:33.290+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:18:33.290+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T16:18:33.290+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:18:33.969+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.722 seconds
[2023-04-23T16:21:56.831+0200] {processor.py:153} INFO - Started process (PID=52979) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:21:56.836+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T16:21:56.837+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:21:56.837+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:21:56.876+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:21:56.875+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T16:21:56.876+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:21:56.876+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T16:21:56.876+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:21:57.608+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.778 seconds
[2023-04-23T16:25:31.768+0200] {processor.py:153} INFO - Started process (PID=53210) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:25:31.772+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T16:25:31.772+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:25:31.772+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:25:31.811+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:25:31.811+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T16:25:31.812+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:25:31.812+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T16:25:31.812+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:25:32.494+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.727 seconds
[2023-04-23T16:29:09.919+0200] {processor.py:153} INFO - Started process (PID=53440) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:29:09.923+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T16:29:09.923+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:29:09.923+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:29:09.959+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:29:09.958+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T16:29:09.959+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:29:09.959+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T16:29:09.959+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:29:10.578+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.659 seconds
[2023-04-23T16:32:38.450+0200] {processor.py:153} INFO - Started process (PID=53673) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:32:38.454+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T16:32:38.454+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:32:38.454+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:32:38.495+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:32:38.495+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T16:32:38.495+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:32:38.495+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T16:32:38.496+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:32:39.139+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.690 seconds
[2023-04-23T16:35:57.997+0200] {processor.py:153} INFO - Started process (PID=53905) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:35:58.000+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T16:35:58.000+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:35:58.000+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:35:58.036+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:35:58.036+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T16:35:58.036+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:35:58.036+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T16:35:58.036+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:35:58.663+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.668 seconds
[2023-04-23T16:39:29.923+0200] {processor.py:153} INFO - Started process (PID=54136) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:39:29.926+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T16:39:29.927+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:39:29.927+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:39:29.962+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:39:29.962+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T16:39:29.963+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:39:29.962+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T16:39:29.963+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:39:30.578+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.655 seconds
[2023-04-23T16:43:05.485+0200] {processor.py:153} INFO - Started process (PID=54366) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:43:05.489+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T16:43:05.490+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:43:05.490+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:43:05.534+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:43:05.533+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T16:43:05.534+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:43:05.534+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T16:43:05.534+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:43:06.238+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.754 seconds
[2023-04-23T16:48:35.537+0200] {processor.py:153} INFO - Started process (PID=54797) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:48:35.542+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T16:48:35.542+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:48:35.542+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:48:35.591+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:48:35.591+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T16:48:35.592+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:48:35.591+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T16:48:35.592+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:48:36.671+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.136 seconds
[2023-04-23T16:54:21.446+0200] {processor.py:153} INFO - Started process (PID=55281) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:54:21.450+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T16:54:21.451+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:54:21.451+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:54:21.512+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:54:21.512+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T16:54:21.512+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:54:21.512+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T16:54:21.513+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:54:22.560+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.115 seconds
[2023-04-23T16:56:55.959+0200] {processor.py:153} INFO - Started process (PID=55407) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:56:55.963+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T16:56:55.964+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:56:55.963+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:56:56.020+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:56:56.019+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T16:56:56.020+0200] {logging_mixin.py:137} INFO - [2023-04-23T16:56:56.020+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T16:56:56.021+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T16:56:56.841+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.883 seconds
[2023-04-23T17:01:34.266+0200] {processor.py:153} INFO - Started process (PID=55656) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:01:34.271+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T17:01:34.272+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:01:34.272+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:01:34.324+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:01:34.324+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T17:01:34.325+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:01:34.324+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T17:01:34.325+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:01:35.082+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.817 seconds
[2023-04-23T17:05:16.943+0200] {processor.py:153} INFO - Started process (PID=55889) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:05:16.947+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T17:05:16.948+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:05:16.948+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:05:16.988+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:05:16.988+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T17:05:16.988+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:05:16.988+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T17:05:16.988+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:05:17.680+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.738 seconds
[2023-04-23T17:08:43.350+0200] {processor.py:153} INFO - Started process (PID=56128) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:08:43.355+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T17:08:43.355+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:08:43.355+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:08:43.391+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:08:43.390+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T17:08:43.391+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:08:43.391+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T17:08:43.391+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:08:44.020+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.671 seconds
[2023-04-23T17:11:58.479+0200] {processor.py:153} INFO - Started process (PID=56356) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:11:58.483+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T17:11:58.483+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:11:58.483+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:11:58.519+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:11:58.519+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T17:11:58.519+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:11:58.519+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T17:11:58.519+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:11:59.132+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.654 seconds
[2023-04-23T17:15:17.799+0200] {processor.py:153} INFO - Started process (PID=56581) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:15:17.803+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T17:15:17.803+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:15:17.803+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:15:17.842+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:15:17.842+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T17:15:17.842+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:15:17.842+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T17:15:17.842+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:15:18.442+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.644 seconds
[2023-04-23T17:18:34.568+0200] {processor.py:153} INFO - Started process (PID=56817) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:18:34.571+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T17:18:34.571+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:18:34.571+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:18:34.607+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:18:34.607+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T17:18:34.608+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:18:34.608+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T17:18:34.608+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:18:35.210+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.643 seconds
[2023-04-23T17:33:36.831+0200] {processor.py:153} INFO - Started process (PID=57108) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:33:36.837+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T17:33:36.838+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:33:36.838+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:33:36.908+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:33:36.907+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T17:33:36.908+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:33:36.908+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T17:33:36.909+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:33:37.995+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.165 seconds
[2023-04-23T17:36:26.328+0200] {processor.py:153} INFO - Started process (PID=57230) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:36:26.334+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T17:36:26.337+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:36:26.335+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:36:26.426+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:36:26.425+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T17:36:26.426+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:36:26.426+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T17:36:26.426+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:36:27.763+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.436 seconds
[2023-04-23T17:39:10.338+0200] {processor.py:153} INFO - Started process (PID=57352) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:39:10.344+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T17:39:10.345+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:39:10.345+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:39:10.395+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:39:10.394+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T17:39:10.395+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:39:10.395+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T17:39:10.396+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:39:11.178+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.842 seconds
[2023-04-23T17:44:14.238+0200] {processor.py:153} INFO - Started process (PID=57586) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:44:14.247+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T17:44:14.247+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:44:14.247+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:44:14.308+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:44:14.307+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T17:44:14.309+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:44:14.308+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T17:44:14.309+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:44:15.362+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.125 seconds
[2023-04-23T17:49:18.208+0200] {processor.py:153} INFO - Started process (PID=57819) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:49:18.214+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T17:49:18.215+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:49:18.215+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:49:18.281+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:49:18.280+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T17:49:18.282+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:49:18.282+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T17:49:18.282+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:49:19.359+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.153 seconds
[2023-04-23T17:51:49.526+0200] {processor.py:153} INFO - Started process (PID=57951) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:51:49.530+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T17:51:49.530+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:51:49.530+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:51:49.570+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:51:49.570+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T17:51:49.570+0200] {logging_mixin.py:137} INFO - [2023-04-23T17:51:49.570+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T17:51:49.570+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T17:51:50.200+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.675 seconds
[2023-04-23T19:31:17.998+0200] {processor.py:153} INFO - Started process (PID=58116) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T19:31:18.002+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T19:31:18.002+0200] {logging_mixin.py:137} INFO - [2023-04-23T19:31:18.002+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T19:31:18.036+0200] {logging_mixin.py:137} INFO - [2023-04-23T19:31:18.036+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T19:31:18.036+0200] {logging_mixin.py:137} INFO - [2023-04-23T19:31:18.036+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T19:31:18.036+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T19:31:18.675+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.678 seconds
[2023-04-23T19:33:19.562+0200] {processor.py:153} INFO - Started process (PID=58236) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T19:33:19.565+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T19:33:19.565+0200] {logging_mixin.py:137} INFO - [2023-04-23T19:33:19.565+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T19:33:19.601+0200] {logging_mixin.py:137} INFO - [2023-04-23T19:33:19.601+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T19:33:19.602+0200] {logging_mixin.py:137} INFO - [2023-04-23T19:33:19.602+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T19:33:19.602+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T19:33:20.296+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.735 seconds
[2023-04-23T19:36:35.052+0200] {processor.py:153} INFO - Started process (PID=58462) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T19:36:35.055+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T19:36:35.056+0200] {logging_mixin.py:137} INFO - [2023-04-23T19:36:35.055+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T19:36:35.091+0200] {logging_mixin.py:137} INFO - [2023-04-23T19:36:35.091+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T19:36:35.092+0200] {logging_mixin.py:137} INFO - [2023-04-23T19:36:35.092+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T19:36:35.092+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T19:36:35.700+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.649 seconds
[2023-04-23T19:39:53.776+0200] {processor.py:153} INFO - Started process (PID=58689) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T19:39:53.779+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T19:39:53.779+0200] {logging_mixin.py:137} INFO - [2023-04-23T19:39:53.779+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T19:39:53.817+0200] {logging_mixin.py:137} INFO - [2023-04-23T19:39:53.816+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T19:39:53.817+0200] {logging_mixin.py:137} INFO - [2023-04-23T19:39:53.817+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T19:39:53.818+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T19:39:54.463+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.688 seconds
[2023-04-23T19:43:23.979+0200] {processor.py:153} INFO - Started process (PID=58914) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T19:43:23.982+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T19:43:23.983+0200] {logging_mixin.py:137} INFO - [2023-04-23T19:43:23.983+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T19:43:24.022+0200] {logging_mixin.py:137} INFO - [2023-04-23T19:43:24.021+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T19:43:24.022+0200] {logging_mixin.py:137} INFO - [2023-04-23T19:43:24.022+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T19:43:24.022+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T19:43:24.714+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.736 seconds
[2023-04-23T19:46:44.735+0200] {processor.py:153} INFO - Started process (PID=59146) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T19:46:44.738+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T19:46:44.738+0200] {logging_mixin.py:137} INFO - [2023-04-23T19:46:44.738+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T19:46:44.773+0200] {logging_mixin.py:137} INFO - [2023-04-23T19:46:44.772+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T19:46:44.773+0200] {logging_mixin.py:137} INFO - [2023-04-23T19:46:44.773+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T19:46:44.773+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T19:46:45.381+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.646 seconds
[2023-04-23T19:50:33.411+0200] {processor.py:153} INFO - Started process (PID=59398) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T19:50:33.415+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T19:50:33.415+0200] {logging_mixin.py:137} INFO - [2023-04-23T19:50:33.415+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T19:50:33.453+0200] {logging_mixin.py:137} INFO - [2023-04-23T19:50:33.452+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T19:50:33.453+0200] {logging_mixin.py:137} INFO - [2023-04-23T19:50:33.453+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T19:50:33.453+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T19:50:34.083+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.673 seconds
[2023-04-23T19:53:54.204+0200] {processor.py:153} INFO - Started process (PID=59624) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T19:53:54.207+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T19:53:54.208+0200] {logging_mixin.py:137} INFO - [2023-04-23T19:53:54.208+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T19:53:54.247+0200] {logging_mixin.py:137} INFO - [2023-04-23T19:53:54.247+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T19:53:54.247+0200] {logging_mixin.py:137} INFO - [2023-04-23T19:53:54.247+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T19:53:54.247+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T19:53:54.890+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.687 seconds
[2023-04-23T19:57:27.084+0200] {processor.py:153} INFO - Started process (PID=59850) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T19:57:27.087+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T19:57:27.089+0200] {logging_mixin.py:137} INFO - [2023-04-23T19:57:27.089+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T19:57:27.127+0200] {logging_mixin.py:137} INFO - [2023-04-23T19:57:27.126+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T19:57:27.127+0200] {logging_mixin.py:137} INFO - [2023-04-23T19:57:27.127+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T19:57:27.127+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T19:57:27.777+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.693 seconds
[2023-04-23T20:01:13.884+0200] {processor.py:153} INFO - Started process (PID=60081) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:01:13.887+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T20:01:13.887+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:01:13.887+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:01:13.924+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:01:13.924+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T20:01:13.924+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:01:13.924+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T20:01:13.924+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:01:14.578+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.695 seconds
[2023-04-23T20:04:45.910+0200] {processor.py:153} INFO - Started process (PID=60309) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:04:45.913+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T20:04:45.914+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:04:45.914+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:04:45.951+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:04:45.950+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T20:04:45.951+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:04:45.951+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T20:04:45.951+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:04:46.691+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.782 seconds
[2023-04-23T20:08:42.114+0200] {processor.py:153} INFO - Started process (PID=60541) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:08:42.117+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T20:08:42.118+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:08:42.118+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:08:42.166+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:08:42.166+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T20:08:42.167+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:08:42.166+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T20:08:42.167+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:08:43.013+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.901 seconds
[2023-04-23T20:12:28.000+0200] {processor.py:153} INFO - Started process (PID=60772) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:12:28.003+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T20:12:28.004+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:12:28.004+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:12:28.040+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:12:28.040+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T20:12:28.040+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:12:28.040+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T20:12:28.040+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:12:28.688+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.689 seconds
[2023-04-23T20:16:13.397+0200] {processor.py:153} INFO - Started process (PID=61006) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:16:13.403+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T20:16:13.404+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:16:13.403+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:16:13.459+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:16:13.459+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T20:16:13.460+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:16:13.459+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T20:16:13.460+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:16:14.475+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.079 seconds
[2023-04-23T20:20:15.759+0200] {processor.py:153} INFO - Started process (PID=61236) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:20:15.763+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T20:20:15.764+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:20:15.764+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:20:15.801+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:20:15.800+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T20:20:15.801+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:20:15.801+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T20:20:15.802+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:20:16.419+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.661 seconds
[2023-04-23T20:23:30.393+0200] {processor.py:153} INFO - Started process (PID=61461) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:23:30.396+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T20:23:30.396+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:23:30.396+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:23:30.429+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:23:30.429+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T20:23:30.429+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:23:30.429+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T20:23:30.430+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:23:31.026+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.634 seconds
[2023-04-23T20:26:45.313+0200] {processor.py:153} INFO - Started process (PID=61686) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:26:45.317+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T20:26:45.317+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:26:45.317+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:26:45.351+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:26:45.351+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T20:26:45.351+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:26:45.351+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T20:26:45.352+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:26:45.948+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.635 seconds
[2023-04-23T20:36:37.528+0200] {processor.py:153} INFO - Started process (PID=61851) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:36:37.531+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T20:36:37.532+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:36:37.532+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:36:37.569+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:36:37.568+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T20:36:37.569+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:36:37.569+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T20:36:37.569+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:36:38.867+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.340 seconds
[2023-04-23T20:38:57.684+0200] {processor.py:153} INFO - Started process (PID=61970) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:38:57.687+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T20:38:57.688+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:38:57.688+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:38:57.730+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:38:57.729+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T20:38:57.730+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:38:57.730+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T20:38:57.730+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:38:58.408+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.725 seconds
[2023-04-23T20:42:52.465+0200] {processor.py:153} INFO - Started process (PID=62198) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:42:52.468+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T20:42:52.469+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:42:52.469+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:42:52.511+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:42:52.511+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T20:42:52.512+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:42:52.512+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T20:42:52.512+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:42:53.167+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.703 seconds
[2023-04-23T20:46:25.937+0200] {processor.py:153} INFO - Started process (PID=62424) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:46:25.940+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T20:46:25.940+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:46:25.940+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:46:25.974+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:46:25.973+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T20:46:25.974+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:46:25.974+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T20:46:25.974+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:46:26.613+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.677 seconds
[2023-04-23T20:50:04.972+0200] {processor.py:153} INFO - Started process (PID=62669) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:50:04.975+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T20:50:04.976+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:50:04.976+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:50:05.014+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:50:05.013+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T20:50:05.014+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:50:05.014+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T20:50:05.014+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:50:05.645+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.674 seconds
[2023-04-23T20:53:56.227+0200] {processor.py:153} INFO - Started process (PID=62914) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:53:56.233+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T20:53:56.233+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:53:56.233+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:53:56.279+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:53:56.278+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T20:53:56.279+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:53:56.279+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T20:53:56.280+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:53:57.041+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.814 seconds
[2023-04-23T20:58:17.382+0200] {processor.py:153} INFO - Started process (PID=63158) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:58:17.386+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T20:58:17.386+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:58:17.386+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:58:17.423+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:58:17.422+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T20:58:17.423+0200] {logging_mixin.py:137} INFO - [2023-04-23T20:58:17.423+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T20:58:17.423+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T20:58:18.558+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.177 seconds
[2023-04-23T21:01:33.207+0200] {processor.py:153} INFO - Started process (PID=63454) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:01:33.209+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T21:01:33.210+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:01:33.210+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:01:33.243+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:01:33.242+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T21:01:33.243+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:01:33.243+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T21:01:33.243+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:01:33.838+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.632 seconds
[2023-04-23T21:05:09.763+0200] {processor.py:153} INFO - Started process (PID=63689) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:05:09.766+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T21:05:09.767+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:05:09.767+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:05:09.810+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:05:09.810+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T21:05:09.810+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:05:09.810+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T21:05:09.810+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:05:10.458+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.696 seconds
[2023-04-23T21:08:42.839+0200] {processor.py:153} INFO - Started process (PID=63933) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:08:42.844+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T21:08:42.844+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:08:42.844+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:08:42.878+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:08:42.878+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T21:08:42.879+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:08:42.879+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T21:08:42.879+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:08:43.470+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.631 seconds
[2023-04-23T21:12:24.152+0200] {processor.py:153} INFO - Started process (PID=64163) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:12:24.156+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T21:12:24.157+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:12:24.156+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:12:24.200+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:12:24.199+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T21:12:24.200+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:12:24.200+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T21:12:24.200+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:12:24.807+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.656 seconds
[2023-04-23T21:15:57.102+0200] {processor.py:153} INFO - Started process (PID=64412) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:15:57.108+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T21:15:57.109+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:15:57.109+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:15:57.156+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:15:57.156+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T21:15:57.157+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:15:57.156+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T21:15:57.157+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:15:57.839+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.739 seconds
[2023-04-23T21:19:35.201+0200] {processor.py:153} INFO - Started process (PID=64671) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:19:35.205+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T21:19:35.206+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:19:35.206+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:19:35.241+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:19:35.241+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T21:19:35.241+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:19:35.241+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T21:19:35.241+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:19:35.962+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.762 seconds
[2023-04-23T21:23:08.479+0200] {processor.py:153} INFO - Started process (PID=64927) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:23:08.482+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T21:23:08.483+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:23:08.483+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:23:08.524+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:23:08.523+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T21:23:08.524+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:23:08.524+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T21:23:08.524+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:23:09.404+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.925 seconds
[2023-04-23T21:26:51.530+0200] {processor.py:153} INFO - Started process (PID=65156) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:26:51.533+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T21:26:51.534+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:26:51.534+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:26:51.571+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:26:51.570+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T21:26:51.571+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:26:51.571+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T21:26:51.571+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:26:52.350+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.820 seconds
[2023-04-23T21:30:22.441+0200] {processor.py:153} INFO - Started process (PID=65382) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:30:22.445+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T21:30:22.445+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:30:22.445+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:30:22.478+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:30:22.478+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T21:30:22.479+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:30:22.479+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T21:30:22.479+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:30:23.087+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.647 seconds
[2023-04-23T21:33:59.127+0200] {processor.py:153} INFO - Started process (PID=65619) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:33:59.132+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T21:33:59.132+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:33:59.132+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:33:59.196+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:33:59.196+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T21:33:59.197+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:33:59.197+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T21:33:59.197+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:34:00.184+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.058 seconds
[2023-04-23T21:40:33.883+0200] {processor.py:153} INFO - Started process (PID=65901) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:40:33.888+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T21:40:33.889+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:40:33.889+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:40:33.930+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:40:33.930+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T21:40:33.931+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:40:33.930+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T21:40:33.931+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:40:34.611+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.728 seconds
[2023-04-23T21:43:49.275+0200] {processor.py:153} INFO - Started process (PID=66124) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:43:49.278+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T21:43:49.279+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:43:49.279+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:43:49.311+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:43:49.311+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T21:43:49.312+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:43:49.311+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T21:43:49.312+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:43:50.013+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.739 seconds
[2023-04-23T21:46:38.335+0200] {processor.py:153} INFO - Started process (PID=66260) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:46:38.338+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T21:46:38.338+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:46:38.338+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:46:38.375+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:46:38.374+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T21:46:38.375+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:46:38.375+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T21:46:38.375+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:46:39.009+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.675 seconds
[2023-04-23T21:50:26.600+0200] {processor.py:153} INFO - Started process (PID=66544) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:50:26.605+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T21:50:26.606+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:50:26.606+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:50:26.659+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:50:26.658+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T21:50:26.659+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:50:26.659+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T21:50:26.660+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:50:27.348+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.749 seconds
[2023-04-23T21:53:56.653+0200] {processor.py:153} INFO - Started process (PID=66773) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:53:56.656+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T21:53:56.657+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:53:56.657+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:53:56.690+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:53:56.689+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T21:53:56.690+0200] {logging_mixin.py:137} INFO - [2023-04-23T21:53:56.690+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T21:53:56.690+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T21:53:57.296+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.643 seconds
[2023-04-23T22:32:37.761+0200] {processor.py:153} INFO - Started process (PID=67073) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T22:32:37.764+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T22:32:37.764+0200] {logging_mixin.py:137} INFO - [2023-04-23T22:32:37.764+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T22:32:37.797+0200] {logging_mixin.py:137} INFO - [2023-04-23T22:32:37.796+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T22:32:37.797+0200] {logging_mixin.py:137} INFO - [2023-04-23T22:32:37.797+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T22:32:37.797+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T22:32:38.388+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.628 seconds
[2023-04-23T22:36:02.604+0200] {processor.py:153} INFO - Started process (PID=67299) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T22:36:02.608+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T22:36:02.609+0200] {logging_mixin.py:137} INFO - [2023-04-23T22:36:02.609+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T22:36:02.654+0200] {logging_mixin.py:137} INFO - [2023-04-23T22:36:02.653+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T22:36:02.654+0200] {logging_mixin.py:137} INFO - [2023-04-23T22:36:02.654+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T22:36:02.654+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T22:36:03.279+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.675 seconds
[2023-04-23T22:38:20.767+0200] {processor.py:153} INFO - Started process (PID=67428) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T22:38:20.770+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T22:38:20.770+0200] {logging_mixin.py:137} INFO - [2023-04-23T22:38:20.770+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T22:38:20.808+0200] {logging_mixin.py:137} INFO - [2023-04-23T22:38:20.807+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T22:38:20.808+0200] {logging_mixin.py:137} INFO - [2023-04-23T22:38:20.808+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T22:38:20.808+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T22:38:21.569+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.803 seconds
[2023-04-23T22:46:35.268+0200] {processor.py:153} INFO - Started process (PID=67704) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T22:46:35.272+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T22:46:35.272+0200] {logging_mixin.py:137} INFO - [2023-04-23T22:46:35.272+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T22:46:35.310+0200] {logging_mixin.py:137} INFO - [2023-04-23T22:46:35.310+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T22:46:35.311+0200] {logging_mixin.py:137} INFO - [2023-04-23T22:46:35.310+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T22:46:35.311+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T22:46:35.953+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.686 seconds
[2023-04-23T22:50:14.919+0200] {processor.py:153} INFO - Started process (PID=67936) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T22:50:14.926+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T22:50:14.927+0200] {logging_mixin.py:137} INFO - [2023-04-23T22:50:14.927+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T22:50:15.001+0200] {logging_mixin.py:137} INFO - [2023-04-23T22:50:15.000+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T22:50:15.001+0200] {logging_mixin.py:137} INFO - [2023-04-23T22:50:15.001+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T22:50:15.003+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T22:50:15.728+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.810 seconds
[2023-04-23T22:54:03.562+0200] {processor.py:153} INFO - Started process (PID=68163) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T22:54:03.567+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-23T22:54:03.568+0200] {logging_mixin.py:137} INFO - [2023-04-23T22:54:03.567+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T22:54:03.608+0200] {logging_mixin.py:137} INFO - [2023-04-23T22:54:03.608+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-23T22:54:03.609+0200] {logging_mixin.py:137} INFO - [2023-04-23T22:54:03.609+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-23T22:54:03.609+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-23T22:54:04.289+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.728 seconds
[2023-04-24T00:43:29.629+0200] {processor.py:153} INFO - Started process (PID=68470) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T00:43:29.635+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-24T00:43:29.635+0200] {logging_mixin.py:137} INFO - [2023-04-24T00:43:29.635+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T00:43:29.671+0200] {logging_mixin.py:137} INFO - [2023-04-24T00:43:29.671+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-24T00:43:29.671+0200] {logging_mixin.py:137} INFO - [2023-04-24T00:43:29.671+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-24T00:43:29.672+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T00:43:30.265+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.637 seconds
[2023-04-24T00:47:06.441+0200] {processor.py:153} INFO - Started process (PID=68703) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T00:47:06.444+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-24T00:47:06.444+0200] {logging_mixin.py:137} INFO - [2023-04-24T00:47:06.444+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T00:47:06.487+0200] {logging_mixin.py:137} INFO - [2023-04-24T00:47:06.486+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-24T00:47:06.487+0200] {logging_mixin.py:137} INFO - [2023-04-24T00:47:06.487+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-24T00:47:06.487+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T00:47:07.141+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.701 seconds
[2023-04-24T00:50:46.025+0200] {processor.py:153} INFO - Started process (PID=68932) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T00:50:46.033+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-24T00:50:46.034+0200] {logging_mixin.py:137} INFO - [2023-04-24T00:50:46.033+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T00:50:46.077+0200] {logging_mixin.py:137} INFO - [2023-04-24T00:50:46.076+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-24T00:50:46.077+0200] {logging_mixin.py:137} INFO - [2023-04-24T00:50:46.077+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-24T00:50:46.077+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T00:50:47.107+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.083 seconds
[2023-04-24T00:54:20.017+0200] {processor.py:153} INFO - Started process (PID=69169) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T00:54:20.022+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-24T00:54:20.023+0200] {logging_mixin.py:137} INFO - [2023-04-24T00:54:20.022+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T00:54:20.060+0200] {logging_mixin.py:137} INFO - [2023-04-24T00:54:20.059+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-24T00:54:20.060+0200] {logging_mixin.py:137} INFO - [2023-04-24T00:54:20.060+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-24T00:54:20.061+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T00:54:20.678+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.662 seconds
[2023-04-24T00:57:37.220+0200] {processor.py:153} INFO - Started process (PID=69395) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T00:57:37.226+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-24T00:57:37.226+0200] {logging_mixin.py:137} INFO - [2023-04-24T00:57:37.226+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T00:57:37.277+0200] {logging_mixin.py:137} INFO - [2023-04-24T00:57:37.277+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-24T00:57:37.277+0200] {logging_mixin.py:137} INFO - [2023-04-24T00:57:37.277+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-24T00:57:37.278+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T00:57:38.176+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.957 seconds
[2023-04-24T01:01:06.270+0200] {processor.py:153} INFO - Started process (PID=69619) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:01:06.275+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-24T01:01:06.276+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:01:06.275+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:01:06.324+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:01:06.323+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-24T01:01:06.324+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:01:06.324+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-24T01:01:06.324+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:01:06.972+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.704 seconds
[2023-04-24T01:05:39.456+0200] {processor.py:153} INFO - Started process (PID=69887) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:05:39.461+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-24T01:05:39.462+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:05:39.462+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:05:39.505+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:05:39.505+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-24T01:05:39.506+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:05:39.506+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-24T01:05:39.506+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:05:40.237+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.783 seconds
[2023-04-24T01:09:20.458+0200] {processor.py:153} INFO - Started process (PID=70110) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:09:20.461+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-24T01:09:20.462+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:09:20.462+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:09:20.502+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:09:20.501+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-24T01:09:20.502+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:09:20.502+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-24T01:09:20.502+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:09:21.212+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.755 seconds
[2023-04-24T01:12:52.167+0200] {processor.py:153} INFO - Started process (PID=70337) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:12:52.170+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-24T01:12:52.171+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:12:52.171+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:12:52.212+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:12:52.212+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-24T01:12:52.213+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:12:52.213+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-24T01:12:52.213+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:12:52.871+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.705 seconds
[2023-04-24T01:16:17.052+0200] {processor.py:153} INFO - Started process (PID=70571) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:16:17.055+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-24T01:16:17.056+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:16:17.056+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:16:17.094+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:16:17.094+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-24T01:16:17.095+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:16:17.095+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-24T01:16:17.095+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:16:17.814+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.763 seconds
[2023-04-24T01:19:36.110+0200] {processor.py:153} INFO - Started process (PID=70795) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:19:36.114+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-24T01:19:36.114+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:19:36.114+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:19:36.159+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:19:36.159+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-24T01:19:36.160+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:19:36.160+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-24T01:19:36.160+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:19:36.789+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.679 seconds
[2023-04-24T01:22:50.810+0200] {processor.py:153} INFO - Started process (PID=71018) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:22:50.813+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-24T01:22:50.814+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:22:50.814+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:22:50.848+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:22:50.848+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-24T01:22:50.849+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:22:50.849+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-24T01:22:50.849+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:22:51.493+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.683 seconds
[2023-04-24T01:26:24.141+0200] {processor.py:153} INFO - Started process (PID=71253) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:26:24.144+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-24T01:26:24.145+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:26:24.145+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:26:24.182+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:26:24.182+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-24T01:26:24.183+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:26:24.183+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-24T01:26:24.183+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:26:24.829+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.689 seconds
[2023-04-24T01:30:03.483+0200] {processor.py:153} INFO - Started process (PID=71482) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:30:03.488+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-24T01:30:03.489+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:30:03.488+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:30:03.538+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:30:03.538+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-24T01:30:03.538+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:30:03.538+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-24T01:30:03.539+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:30:04.634+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.152 seconds
[2023-04-24T01:33:38.566+0200] {processor.py:153} INFO - Started process (PID=71708) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:33:38.570+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-24T01:33:38.571+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:33:38.571+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:33:38.616+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:33:38.615+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-24T01:33:38.616+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:33:38.616+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-24T01:33:38.616+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:33:39.337+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.771 seconds
[2023-04-24T01:37:02.050+0200] {processor.py:153} INFO - Started process (PID=71935) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:37:02.053+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-24T01:37:02.054+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:37:02.054+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:37:02.089+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:37:02.089+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-24T01:37:02.089+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:37:02.089+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-24T01:37:02.090+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:37:02.718+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.668 seconds
[2023-04-24T01:40:20.410+0200] {processor.py:153} INFO - Started process (PID=72158) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:40:20.413+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-24T01:40:20.413+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:40:20.413+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:40:20.448+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:40:20.448+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-24T01:40:20.448+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:40:20.448+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-24T01:40:20.448+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:40:21.049+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.640 seconds
[2023-04-24T01:43:38.178+0200] {processor.py:153} INFO - Started process (PID=72381) to work on /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:43:38.181+0200] {processor.py:743} INFO - Processing file /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-04-24T01:43:38.181+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:43:38.181+0200] {dagbag.py:532} INFO - Filling up the DagBag from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:43:38.213+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:43:38.213+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-04-24T01:43:38.214+0200] {logging_mixin.py:137} INFO - [2023-04-24T01:43:38.213+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-04-24T01:43:38.214+0200] {processor.py:755} WARNING - No viable dags retrieved from /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-04-24T01:43:38.807+0200] {processor.py:175} INFO - Processing /Users/siddalingkattimani/dbt_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.630 seconds
